# Copy this file to .env and fill in your values

# ── Required ─────────────────────────────────────────────────────────────────

GOOGLE_API_KEY= 'AIzaSyBpt7INw2cMRICoXDDBI7_O5_8n4r07QYM'

# ── Optional ──────────────────────────────────────────────────────────────────
PROMETHEUS_URL='http://localhost:9090'
SLACK_WEBHOOK_URL='https://hooks.slack.com/services/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UTES=5'
